# -*- coding: utf-8 -*-
"""LH_CD_ANTONIONETO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Io4BHAA8_G4fGR6597kpeTz73OyNwt3T

# Análise Exploratória de Dados (EDA)
Montagem inicial da análise exploratória de dados.
"""

import pandas as pd

file_path = 'data/teste_indicium_precificacao.csv'
df = pd.read_csv(file_path)
df = df[df['price'] > 0]
df = df[df['disponibilidade_365'] > 0]
df = df.drop(['host_id', 'host_name', 'ultima_review', 'calculado_host_listings_count'], axis=1)
df.describe()

"""A primeira análise feita foi de distribuição de preços para verificar se existe grande variação de valores no dataset."""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))
sns.histplot(df['price'], bins=50, kde=True)
plt.title('Distribuição de Preços')
plt.show()

"""Análise dos valores e identificação de outliers. Foi feita a remoção dos itens com esses valores para não criar ruídos na análise final."""

import numpy as np

Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)
IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

print("Q1R:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Limite Inferior:", limite_inferior)
print("Limite Superior:", limite_superior)

df = df[(df['price'] >= limite_inferior) & (df['price'] <= limite_superior)]

df.describe()

sns.boxplot(data=df, x=df['price'])
plt.title("Boxplot dos preços de aluguel por noite")
plt.show()

"""Após a análise dos preços, foi verificada a localização dos imóveis, para entender se existe algum padrão geográfico presente que possa ser levado em consideração."""

plt.figure(figsize=(10, 6))
sns.scatterplot(x=df['longitude'], y=df['latitude'], hue=df['price'], alpha=0.5)
plt.title("Distribuição Geográfica dos Imóveis")
plt.show()

"""Também foi feito o agrupamento de ofertas por bairro. Abaixo, a exibição do quantitativo geral e, em seguida, gráfico mostrando a variação."""

media_por_bairro = df.groupby('bairro_group')['price'].mean()
media_por_bairro.sort_values(ascending=False)

plt.figure(figsize=(9, 5))
sns.barplot(x=media_por_bairro.values, y=media_por_bairro.index)

plt.xlabel('Preço médio')
plt.ylabel('Bairro do imóvel')
plt.title('Preço médio por bairro')
plt.show()

"""O próximo passo foi analisar se o tipo de oferta tem influência direta no valor final do aluguel."""

plt.figure(figsize=(10, 5))
sns.boxplot(x=df['price'], y=df['room_type'])
plt.title("Preço por tipologia de oferta")
plt.show()

df.groupby('room_type')['price'].describe()

"""A seguir, a disponibilidade do local e o tempo mínimo de estadia foram analisado em busca de padrões, além do seu impacto no preço."""

plt.figure(figsize=(9, 5))
sns.histplot(df['disponibilidade_365'], bins=10, kde=True)
plt.title("Verificação de disponibilidade")
plt.show()

plt.figure(figsize=(9, 5))
sns.scatterplot(x=df['disponibilidade_365'], y=df['price'], alpha=0.5)
plt.title("Relação entre disponibilidade e o preço")
plt.show()

df[df['minimo_noites'] < 365]['minimo_noites'].hist(bins=50)
plt.title("Distribuição de noites mínimas")
plt.show()

plt.figure(figsize=(9, 5))
sns.scatterplot(x=df['minimo_noites'], y=df['price'], alpha=0.5)
plt.title("Relação entre mínimo de noites e preço")
plt.show()

"""O próximo tópico analisando juntamente ao preço foram as reviews feitas pelos visitantes, seja na quantidade geral ou na verificação por mês."""

plt.figure(figsize=(9, 5))
sns.histplot(df['numero_de_reviews'], bins=50, kde=True)
plt.title("Verificação da quantidade de reviews")
plt.show()

plt.figure(figsize=(9, 5))
sns.histplot(df['reviews_por_mes'], bins=50, kde=True)
plt.title("Verificação da quantidade de reviews por mês")
plt.show()

plt.figure(figsize=(9, 5))
sns.scatterplot(x=df['numero_de_reviews'], y=df['price'], alpha=0.5)
plt.title("Relação entre número de reviews e o preço")
plt.show()

"""A última verificação feita buscou entender se a nomenclatura do local interfere ou não no preço do aluguel."""

from collections import Counter

mediana_precos = df['price'].median()
nomes_mais_caros = " ".join(df[df['price'] > mediana_precos]['nome'].dropna().tolist()).lower().split()
nomes_mais_baratos = " ".join(df[df['price'] < mediana_precos]['nome'].dropna().tolist()).lower().split()

contagem_nomes_caros = sorted(Counter(nomes_mais_caros).most_common(20), key=lambda x: x[1], reverse=True)
contagem_nomes_baratos = sorted(Counter(nomes_mais_baratos).most_common(20), key=lambda x: x[1], reverse=True)

print("Quantidade de itens encontrados em anúncios caros:", len(contagem_nomes_caros))
print("Palavras mais comuns em anúncios caros:")
for palavra, contagem in contagem_nomes_caros:
    print(f" - {palavra}: {contagem}")

print("\nQuantidade de itens encontrados em anúncios baratos:", len(contagem_nomes_baratos))
print("Palavras mais comuns em anúncios baratos:")
for palavra, contagem in contagem_nomes_baratos:
    print(f" - {palavra}: {contagem}")